/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.application.Application;
import javafx.stage.Stage;


public class App extends Application{
    @Override
    public void start(Stage stage) {
        stage.setTitle("Patcher");
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
