/*
 * This source file was generated by the Gradle 'init' task
 */
package net.chrupki;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        Patcher classUnderTest = new Patcher();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
