/*
 * This source file was generated by the Gradle 'init' task
 */
package net.chrupki;


import javafx.application.Application;
import javafx.scene.control.Button;
import javafx.scene.Parent;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.scene.Scene;
import javafx.stage.Stage;
import net.chrupki.database.DatabaseInitializer;
import net.chrupki.project.AppProject;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.IOException;


public class Patcher extends Application{

    private Parent parent;

    @Override
    public void start(Stage stage) throws Exception {
        DatabaseInitializer.InitDB();
        AppProject.FetchProject();
        AppPaths.GetDataDir();


        {
            stage.setTitle("Text Input App");
            stage.setMinWidth(600);
            stage.setMinHeight(400);

            TextField txtf = new TextField("Project");
            Button btn = new Button("Create Project");

            btn.setOnAction(e -> {
                AppProject.CreateProject(txtf.getText());
            });

            VBox root = new VBox(10);
            root.getChildren().addAll(txtf, btn);

            Scene scene = new Scene(root, 400, 200);
            stage.setScene(scene);
            stage.show();

        }
    }

    public static void main(String[] args) {
        launch();
    }
}
