/*
 * This source file was generated by the Gradle 'init' task
 */
package net.chrupki;


import javafx.application.Application;
import javafx.scene.Parent;
import javafx.stage.Stage;
import net.chrupki.database.DatabaseInitializer;
import net.chrupki.project.AppProject;


public class Patcher extends Application{

    private Parent parent;

    @Override
    public void start(Stage stage) {
        DatabaseInitializer.InitDB();
        stage.setTitle("Text Input App");

        // AppPaths.GetDataDir();

        stage.setMinWidth(600);
        stage.setMinHeight(400);

        // AppProject.CreateProject("cotv");

        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
